### ISSUE TITLE
Auto and Cut transitions not working (Need to accept int value & float value)

### ISSUE THREAD

**Issue by seanathonedward** [danielbuechele/atemOSC#43] opened 2017-10-04 19:25 UTC
Using Qlab and Atem OSC (using OSC protocol) I cannot get the Auto and Cut transitions to work. All other functions I have tried work well.

**Comment by SteffeyDev** [comment] 2017-10-05 04:03
What are the exact OSC commands that are not working?  And does the AtemOSC log show that they are received?  You can open the log from the help menu

**Comment by seanathonedward** [comment] 2017-10-05 10:10
the two that are not working are these:

**/atem/transition/auto
/atem/transition/cut**

The log shows that they are received, but nothing happens. For reference, the command 

**/atem/transition/ftb**

works perfectly.

**Comment by sneat** [comment] 2017-10-05 10:21
@seanathonedward are you sending a value along with the command? e.g.

`/atem/transition/auto 1`

![image](https://user-images.githubusercontent.com/293277/31222529-ba3fbfe4-aa0a-11e7-9132-e0267c122c54.png)

**Comment by seanathonedward** [comment] 2017-10-05 13:47
I have NOT tried that. Once I get my hands on my switcher again, I'll give it a go and report back

**Comment by seanathonedward** [comment] 2017-10-12 20:23
Tried this today - still not working

**Comment by sneat** [comment] 2017-10-13 00:33
Can you take a screenshot of the value you're sending, along with the relevant part of QLab OSC configuration and also a screenshot of atemOSC (showing the OSC port)?

**Comment by lotech** [comment] 2017-11-06 20:03
I can confirm this isn't working on my ATDM TV Studio HD. FTP is working just not switching cut/auto.
Log is reporting - 
[2017-11-07 09:02:23] Received OSC message: /atem/transition/auto	Value: <OSCVal i 1>
[2017-11-07 09:02:28] Received OSC message: /atem/transition/auto	Value: <OSCVal i 1>
[2017-11-07 09:02:31] Received OSC message: /atem/transition/auto	Value: <OSCVal i 2>
[2017-11-07 09:02:35] Received OSC message: /atem/transition/auto	Value: (null)
[2017-11-07 09:02:56] Received OSC message: /atem/transition/ftb	Value: (null)
[2017-11-07 09:03:03] Received OSC message: /atem/transition/auto	Value: (null)

**Comment by lotech** [comment] 2017-11-06 20:09
Also confirming I can crash the app sometimes sending /atem/transition/auto

**Comment by SteffeyDev** [comment] 2017-11-06 21:37
The logs indicate that your OSC device is sending null values, which would certainly produce undefined behavior. The officially supported value is a float value of 1, though it may also support an int value of 1 as well.  It is possible that these null values are canceling out the previously received values. Can you test again but only send a float or int value of 1 to atemOSC?

**Comment by lotech** [comment] 2017-11-06 21:42
Tried /atem/transition/auto 0 in qlab to no success (and 1 also)

**Comment by SteffeyDev** [comment] 2017-11-06 21:52
What version of AtemOSC are you running? And can qlab send float values?

**Comment by lotech** [comment] 2017-11-06 21:54
2.4.7 so the current build. I can send send float/ints when I set a fade in OSC in qlab - I set the from - to to both 1 to send one and both to 0 to send 0.

**Comment by SteffeyDev** [comment] 2017-11-06 22:01
I’ve never used qlab, but maybe try setting both the from and to values to 1 as float, or only send from value.  Ideally you want to just send the 1 float value once (see picture above).  @sneat or I can test to see if we can find the issue, but I won’t be able to until next Sunday.

**Comment by lotech** [comment] 2017-11-06 22:09
I tried just with a single 1 after the command with no luck. Definitely getting a lot of crashes on 10.12.6 also.

**Comment by lotech** [comment] 2017-11-06 23:06
We got it - needed to send 1.0 with /atem/transition/auto. Thanks for helping through the process

**Comment by SteffeyDev** [comment] 2017-11-06 23:24
@lotech Glad you figured it out! I will leave this ticket open so that we can investigate whether we can accept int values of 1 as well as float values, to prevent future issues like this

**Comment by SteffeyDev** [comment] 2018-02-09 00:33
Delete “<all args>” and put a “1” and press enter. Then click the drop down arrow that appears next to the 1 and select “float”

**Comment by eskimograph** [comment] 2018-02-20 17:13
I start using MilluminV2 and Atem OSC (using OSC protocol) I cannot get the Auto and Cut transitions to work. Other functions I have tried work well (/atem/transition/ftb) (/atem/program/1) etc..
I work with Atem 1M/E production / software 7.3 on macOS 10.13
log is reporting:
[2018-02-20 17:43:02] Received OSC message: /atem/transition/auto	Value: <OSCVal i 0>
[2018-02-20 17:43:02] You must specify a transition action of 'bar', 'cut', 'auto', 'ftb', or 'set-type
[2018-02-20 17:43:02] Received OSC message: /atem/transition/auto	Value: <OSCVal i 1024>
[2018-02-20 17:43:02] You must specify a transition action of 'bar', 'cut', 'auto', 'ftb', or 'set-type
[2018-02-20 17:43:02] Received OSC message: /atem/transition/auto	Value: <OSCVal i 1>
[2018-02-20 17:43:02] You must specify a transition action of 'bar', 'cut', 'auto', 'ftb', or 'set-type
I try to send: /atem/transition/auto 1.      and          /atem/transition/auto 1.0
nothing happen

**Comment by SteffeyDev** [comment] 2018-02-20 17:53
It looks from the log that you only tried sending integer values, can you show the log when you send `/atem/transition/auto` with a float value of 1?

**Comment by eskimograph** [comment] 2018-02-20 18:01
log report  /atem/transition/auto 1.0
[2018-02-20 19:00:17] Received OSC message: /atem/transition/auto 1.0	Value: <OSCVal i 0>
[2018-02-20 19:00:17] You must specify a transition action of 'bar', 'cut', 'auto', 'ftb', or 'set-type
[2018-02-20 19:00:17] Received OSC message: /atem/transition/auto 1.0	Value: <OSCVal i 1024>
[2018-02-20 19:00:17] You must specify a transition action of 'bar', 'cut', 'auto', 'ftb', or 'set-type
[2018-02-20 19:00:17] Received OSC message: /atem/transition/auto 1.0	Value: <OSCVal i 0>
[2018-02-20 19:00:17] You must specify a transition action of 'bar', 'cut', 'auto', 'ftb', or 'set-type

**Comment by SteffeyDev** [comment] 2018-02-20 18:23
I software yuk are using to send the values is doing so incorrectly, it appears from the logs that what you are actually sending is an OSC message with the address “/atem/transition/auto 1.0” and an integer value of “0” (hence the “<OSCVal I 0>”.  You need to send an OSC message with the address “/atem/transition/auto” and a float value of “1.0”, which would show in the logs as “<OSCVal f 1.0>”.  

I’m not familiar with MilluminV2, is that the software you are using to send the OSC messages?

**Comment by eskimograph** [comment] 2018-02-20 19:28
yes, MilluminV2 can send midi, osc, dmx with a data track 
and for the moment I test this message for atem : 
sources ok  
upstream keyers ok
transitions ok with fade to black and it take the time gave in transition in atem 
Issues with cut, auto cut.  
With bar it works if I send a float but it is change by a "cut way", no time for the transition...
[2018-02-20 20:24:58] Received OSC message: /atem/transition/bar	Value: <OSCVal i 0>
[2018-02-20 20:24:58] Received OSC message: /atem/transition/bar	Value: <OSCVal i 1024>
[2018-02-20 20:24:58] Received OSC message: /atem/transition/bar	Value: <OSCVal f 1.500000>
<img width="486" alt="capture d ecran 2018-02-20 a 20 24 02" src="https://user-images.githubusercontent.com/36667055/36444714-61dd4acc-167c-11e8-9d00-0da4b23147ab.png">

**Comment by SteffeyDev** [comment] 2018-02-20 20:52
What happens if you set your current value to 1.0 for `auto`?  It looks like it will still through warnings from the range value sends but also should work.

I downloaded the software but won't be able to test until Thursday or Sunday.

**Comment by SteffeyDev** [comment] 2018-02-20 21:02
@danielbuechele the reason we've been having problems with this is because the `/atem/transition/auto` and `/atem/transition/cut` commands only work if they are accompanied by a float value of `1.0`.  `/atem/transition/ftb` works without even checking the value?  What was the original motivation for having a value check on `auto` and `cut`?

**Comment by eskimograph** [comment] 2018-02-21 20:26
sorry,  I can't work at the moment on atem and Millumin, perhaps tomorrow evening, I hope

**Comment by SteffeyDev** [comment] 2018-02-27 15:48
@danielbuechele Friendly ping, still wondering about my last comment

**Comment by eskimograph** [comment] 2018-02-27 17:47
Still not working (millumin to Atem) with  /atem/transition/auto and /atem/transition/cut when I send 1.0
But this adresses  work well with Isadora to Atem 
In Millumin, /atem/transition/bar work when I checked follow transition.
Millumin send succession of float number to atem.
It's apply the time of transition fixed in millumin (don't take the time in atem) but when it's finished the T BAR come back suddenly at the first position.
For the moment I can't test as I want millumin and Atem, sorry for the late in answer

I have a new question (out of this issue), is there a way with adresses osc for adjusting clip and gain in luma key?
Thanks for your patience

**Comment by SteffeyDev** [comment] 2018-03-27 16:01
Ok, I think the issue is definitely on the Millumin side, though with the lack of response of @danielbuechele I am considering making an executive decision and removing the value checks on `auto` and `cut`, which should allow Millumin to work.

As fo the luma key question, unfortunately we only support the OSC addresses listed on the Readme, so any functionality not detailed there is not available.

**Comment by eskimograph** [comment] 2018-03-27 22:13
Thanks for your answer.
At the moment I find a way for rehearsal, using osculator to control atem by (cut / Tbar / program and preview cam). with a nanokorg.
and for the show in Millumin, I use macros, (i can change and edit in xml as explain by john/tuto/here torecord).

**Comment by SteffeyDev** [comment] 2018-07-04 16:09
Ok, in v2.5.4 you should now be able to send the auto and cut transition commands without any values, and they should still be received and processed.

**Closed by SteffeyDev** 2018-07-04 16:09 UTC
Labels: enhancement, pending-close
