### ISSUE TITLE
atemOSC 2.5.6 Cut and Auto not working

### ISSUE THREAD

**Issue by edmunden** [danielbuechele/atemOSC#120] opened 2019-03-24 08:55 UTC
Im using oslulator 3.3.0 .. the cut and auto function not working after I update from atem osc 2.5.4.. previous version was working fine.
Thanks.

**Comment by officialmattsnyder** [comment] 2019-05-15 17:28
I'm experiencing this too. Behavior is pretty intermittent with me.

Most common behavior is that a transition will execute and then "undo" itself 2-3 seconds later. Every once in a while the auto transition will just "freeze" at a 50/50 blend of the 2 sources.

I'm trying to narrow down exactly where the problem is coming from.

- Sending duplicate Midi to Osculator (I've pretty much ruled this out)
- Sending duplicate OSC from Osculator to ATEM (Not even sure where to start on this one)
- atemOSC double executing a single osc message. (I'm in process on this one, should have answers soonish)

Hopefully that's helpful data

**Comment by randallpacker** [comment] 2019-05-15 17:35
I believe the problem with controlling the ATEM transition bar is related to sending too much data. I would have crashes after quitting atemOSC, and very occasionally while in use, when sending steady streams of data to the transition bar. I was able to resolve this problem in MaxMSP by putting a speedlim object on the dataflow, with a maximum speed limit of 200ms between values. This seemed to have resolved the crashes. Perhaps there is a way to do something like that in Osculator?

**Comment by bullypro** [comment] 2019-06-26 04:59
Anybody resolve this? I'm having the same issue. When I hit Cut, it will do the action but switch back instantly.

**Comment by officialmattsnyder** [comment] 2019-06-26 16:41
I never actually "solved" it, but I was able to isolate the problem to OSCulator. So, I bypassed it and am now sending OSC commands directly to ATEM. Which actually winds up being a much more elegant solution.

**Comment by bullypro** [comment] 2019-06-26 16:55
Thanks. I am very new to this and only know how to use OSCulator to send commands. Do you have any links to show me how I would bybass and send OSC commands directly to ATEM? or is it something you can easily explain? Thank you.

**Comment by officialmattsnyder** [comment] 2019-06-26 16:57
What are you using to send data into osculator in the first place?

**Comment by bullypro** [comment] 2019-06-26 17:02
I'm using a Behringer X-Touch Mini and Blackmagic ATEM Television Studio HD

using software OSCultor, atemOSC, ATEM Switcher Software

**Comment by officialmattsnyder** [comment] 2019-06-26 17:07
Gotcha. With that set up you'll need to probably keep OSCulator as I don't think the xtouch is capable of sending OSC commands.

For what it's worth https://bitfocus.io/companion/ would be worth checking out. It's a much better solution with a lot more capability than what you're currently doing

**Comment by randallpacker** [comment] 2019-06-26 17:39
I am using Max/MSP/Jitter to send commands directly to ATEM. I believe there is a sample Max Patch in the docs. Max is great for integrating MIDI, OSC, audio and video.

**Comment by bullypro** [comment] 2019-06-26 18:06
I'll definitely check out Companion. Thank you.

**Comment by Josedesosua** [comment] 2019-06-28 14:45
> I'm using a Behringer X-Touch Mini and Blackmagic ATEM Television Studio HD
> 
Software: OSCulator 3.3.0, atemOSC 2.5.6, ATEM Software Control 8.0

Precisely I am having the same problem as bullypro.  Cut, Auto and FTB.  Cut just works by keeping the key pressed, then returns to previous state.  For Auto and FTB the effect is gradual.  I have to keep pressing the key  until the transition completes but then it goes back to previous state. Any help is appreciated.

**Comment by SteffeyDev** [comment] 2019-06-28 16:26
I am fairly certain the reason you are seeing this behavior is because when you press a physical or midi button, it actually sends two signals: a 1 when the button is pressed, and a 0 when the button is released. atemOSC receives both of these signals and tries to process them both, ignoring the number that was sent. When I had this issue, the fix was to go into OSCulator and add a filter so that signals were only sent on the rising edge (0 -> 1), and then the button release signal (1 -> 0) would be ignored and not sent to atemOSC

**Comment by SteffeyDev** [comment] 2019-06-28 16:29
If needed, I can probably give more specific guidance in how to fix this in OSCulator.

**Comment by Josedesosua** [comment] 2019-06-28 16:52
Thanks Peter for this helpful input.  I am fairly new to Osculator, so I would appreciate some help on how to add this filter.

Enviado desde mi iPhone

El 28 jun. 2019, a la(s) 12:30 p. m., Peter Steffey <notifications@github.com<mailto:notifications@github.com>> escribió:


If needed, I can probably give more specific guidance in how to fix this in OSCulator.

**Comment by bullypro** [comment] 2019-06-28 17:12
> If needed, I can probably give more specific guidance in how to fix this in OSCulator.

Yes, that would be very helpful. Thank you!

**Comment by SteffeyDev** [comment] 2019-06-28 22:51
Ok.  Settings button (top right corner), OSC routes tab, double-click on the route for /atem/transition/auto to bring up the OSC Template Editor, then at the bottom change "Send When" to "value crosses 0.5 upwards".  Do the same with /atem/transition/ftp and /atem/transition/cut.  This should trigger the transition only on button press, not release.  If you want to trigger on only release instead, you can select "value crosses 0.5 downwards".  Obviously some of the other options there may work as well.

**Comment by SteffeyDev** [comment] 2019-06-28 22:53
If you don't have a route for those paths you may have to create them first.  Let me know if you still can't figure it out.

**Comment by bullypro** [comment] 2019-06-29 01:23
SteffeyDev this worked for me!!!! Thank you so much!

**Comment by Josedesosua** [comment] 2019-06-29 13:34
> If you don't have a route for those paths you may have to create them first. Let me know if you still can't figure it out.

Still can't figure it out.  when adding "value crosses 0.5 upwards", now the button does not respond at all.  I might be missing something here.  Here's a screenshot of my settings. Bullypro, can you offer some insight?
<img width="1282" alt="Screen Shot 2019-06-29 at 9 30 53 AM" src="https://user-images.githubusercontent.com/52289356/60384880-077a6100-9a51-11e9-988d-e58ba0175891.png">

<img width="1250" alt="Screen Shot 2019-06-29 at 9 31 09 AM" src="https://user-images.githubusercontent.com/52289356/60384858-e154c100-9a50-11e9-95f0-c1b8ce7a788d.png">

**Comment by SteffeyDev** [comment] 2019-06-29 15:58
I would recommend experimenting with all the different “Send When” options to see if any of them work.

**Comment by SteffeyDev** [comment] 2019-06-29 16:00
Also, instead of <all args>, you could try just putting 1 (float)

**Comment by bullypro** [comment] 2019-06-29 17:43
> Bullypro, can you offer some insight?

Let me look at my screen and I'll let you know if anything is different. I won't be in front of it till tonight. I do notice a little bit of difference in that in my top message window, if I hit FTB for example, It will show FTB in the top and bottom windows. But not sure that matters any, it's just the way I labeled it. I used this YouTube video to set up everything on my end. Maybe this will help answer anything you did differently from what I did. https://www.youtube.com/watch?v=ooaOz5Uytxs

**Comment by Josedesosua** [comment] 2019-07-01 14:02
> Ok. Settings button (top right corner), OSC routes tab, double-click on the route for /atem/transition/auto to bring up the OSC Template Editor, then at the bottom change "Send When" to "value crosses 0.5 upwards". Do the same with /atem/transition/ftp and /atem/transition/cut. This should trigger the transition only on button press, not release. If you want to trigger on only release instead, you can select "value crosses 0.5 downwards". Obviously some of the other options there may work as well.

Success!  I just created a new file in Osculator and started from scratch. This time it worked!  Thank you so much for your help.

**Comment by Josedesosua** [comment] 2019-07-01 14:12
> > Bullypro, can you offer some insight?
> 
> Let me look at my screen and I'll let you know if anything is different. I won't be in front of it till tonight. I do notice a little bit of difference in that in my top message window, if I hit FTB for example, It will show FTB in the top and bottom windows. But not sure that matters any, it's just the way I labeled it. I used this YouTube video to set up everything on my end. Maybe this will help answer anything you did differently from what I did. https://www.youtube.com/watch?v=ooaOz5Uytxs

It was indeed different.  So I created a new file from scratch and this time it worked!  Thanks.

**Comment by SteffeyDev** [comment] 2019-07-13 00:55
Glad you guys fixed your problems! I’m going to close this as the issue seems to not be with atemOSC, but I have a feeling this thread will be useful in the future.

**Closed by SteffeyDev** 2019-07-13 00:55 UTC

**Comment by tedzstonz2000** [comment] 2021-04-10 20:33
> I am fairly certain the reason you are seeing this behavior is because when you press a physical or midi button, it actually sends two signals: a 1 when the button is pressed, and a 0 when the button is released. atemOSC receives both of these signals and tries to process them both, ignoring the number that was sent. When I had this issue, the fix was to go into OSCulator and add a filter so that signals were only sent on the rising edge (0 -> 1), and then the button release signal (1 -> 0) would be ignored and not sent to atemOSC

can you please send a screen shot of where u put a filter - totally new this as well same issue as everyone else -

**Comment by tedzstonz2000** [comment] 2021-04-10 20:33
can you please send a screen shot of where u put a filter - totally new this as well same issue as everyone else -
