### ISSUE TITLE
no osc sources

### ISSUE THREAD

**Issue by samlesbrises** [danielbuechele/atemOSC#62] opened 2017-12-27 21:40 UTC
hi
there i've setup atemOSC with my ATEM Television Studio HD, I've a trouble to get the OSC adresses for sources, when I clic on OSC adresses in Help menu he don't give me the sources.
I setup with your default instruction for the cam 1 to 8 and it's working, but can't work for media player, color or bar (works for black).
Do you have any idea why I can't get the OSC adresses ?
thanks

**Comment by SteffeyDev** [comment] 2017-12-29 03:40
Unfortunately the in-app address list is a bit out of date, you should use the OSC address list on the github README for the most updated commands.  Is that what you are asking about, or do the commands themselves not work? If a command listed in the README does not work as expected, please respond with the extract command you are having issues with and the SDK version of your Television Studio.

**Comment by SteffeyDev** [comment] 2018-01-10 01:57
@samlesbrises Any update on this?

**Comment by samlesbrises** [comment] 2018-01-10 17:08
hi sorry I was a bit busy by work,
so I saw the OSC address list on the github README, I win to setup the 8 inputs of my ATEM television Studio HD (from`/atem/program/1 to /atem/program/8).
I tried to setup Bars/Colors and Medias but it's not working, obviously the Bars and Color address you gave not work because it used by input 7 and 8, but when I tried 9, 10, 12 or else it's not working. I don't tried yet the others function.
My ATEM softwar control for the ATEM is 7.1.2 so I think the SDK is 7.1 in the ATEM.
Regards

**Comment by sneat** [comment] 2018-01-11 23:58
I can confirm that the OSC addresses window has been broken with one of the more recent updates. @SteffeyDev if you happen to have a chance to take a look at it, it looks like the OSC addresses window is being populated only once, prior to the ATEM connecting (and then never being updated).

@samlesbrises the output of the addresses for an ATEM Television Studio HD should be:

```
Transitions:
	T-Bar: /atem/transition/bar
	Cut: /atem/transition/cut
	Auto-Cut: /atem/transition/auto
	Fade-to-black: /atem/transition/ftb

Transition type:
	Set to Mix: /atem/transition/set-type/mix
	Set to Dip: /atem/transition/set-type/dip
	Set to Wipe: /atem/transition/set-type/wipe
	Set to Stinger: /atem/transition/set-type/sting
	Set to DVE: /atem/transition/set-type/dve

Upstream Keyers:
	On Air KEY 1 toggle: /atem/usk/1
	BKGD: /atem//0
	KEY 1: /atem/nextusk/1

Downstream Keyers:
	Auto-Transistion DSK1: /atem/dsk/1
	Set DSK On Ait1: /atem/dsk/on-air/1	<0|1>
	Tie Next-Transistion DSK1: /atem/dsk/tie/1
	Set Tie Next-Transistion DSK1: /atem/dsk/set-tie/1	<0|1>
	Toggle DSK1: /atem/dsk/toggle/1
	Auto-Transistion DSK2: /atem/dsk/2
	Set DSK On Ait2: /atem/dsk/on-air/2	<0|1>
	Tie Next-Transistion DSK2: /atem/dsk/tie/2
	Set Tie Next-Transistion DSK2: /atem/dsk/set-tie/2	<0|1>
	Toggle DSK2: /atem/dsk/toggle/2

Sources:
	Black: /atem/program/0
	Camera 1: /atem/program/1
	Camera 2: /atem/program/2
	Camera 3: /atem/program/3
	Camera 4: /atem/program/4
	Camera 5: /atem/program/5
	Camera 6: /atem/program/6
	Camera 7: /atem/program/7
	Camera 8: /atem/program/8
	Color Bars: /atem/program/1000
	Color 1: /atem/program/2001
	Color 2: /atem/program/2002
	Media Player 1: /atem/program/3010
	Media Player 1 Key: /atem/program/3011
	Media Player 2: /atem/program/3020
	Media Player 2 Key: /atem/program/3021
	Key 1 Mask: /atem/program/4010
	DSK 1 Mask: /atem/program/5010
	DSK 2 Mask: /atem/program/5020
	Clean Feed 1: /atem/program/7001
	Clean Feed 2: /atem/program/7002
	Auxiliary 1: /atem/program/8001
	Program: /atem/program/10010
	Preview: /atem/program/10011

Aux Outputs:
	Set Aux 1 to Source: /atem/aux/1	<valid_program_source>

Media Players:
	Set MP 1 to Still 1: /atem/mplayer/1/still/1
	Set MP 1 to Still 2: /atem/mplayer/1/still/2
	Set MP 1 to Still 3: /atem/mplayer/1/still/3
	Set MP 1 to Still 4: /atem/mplayer/1/still/4
	Set MP 1 to Still 5: /atem/mplayer/1/still/5
	Set MP 1 to Still 6: /atem/mplayer/1/still/6
	Set MP 1 to Still 7: /atem/mplayer/1/still/7
	Set MP 1 to Still 8: /atem/mplayer/1/still/8
	Set MP 1 to Still 9: /atem/mplayer/1/still/9
	Set MP 1 to Still 10: /atem/mplayer/1/still/10
	Set MP 1 to Still 11: /atem/mplayer/1/still/11
	Set MP 1 to Still 12: /atem/mplayer/1/still/12
	Set MP 1 to Still 13: /atem/mplayer/1/still/13
	Set MP 1 to Still 14: /atem/mplayer/1/still/14
	Set MP 1 to Still 15: /atem/mplayer/1/still/15
	Set MP 1 to Still 16: /atem/mplayer/1/still/16
	Set MP 1 to Still 17: /atem/mplayer/1/still/17
	Set MP 1 to Still 18: /atem/mplayer/1/still/18
	Set MP 1 to Still 19: /atem/mplayer/1/still/19
	Set MP 1 to Still 20: /atem/mplayer/1/still/20
	Set MP 2 to Still 1: /atem/mplayer/2/still/1
	Set MP 2 to Still 2: /atem/mplayer/2/still/2
	Set MP 2 to Still 3: /atem/mplayer/2/still/3
	Set MP 2 to Still 4: /atem/mplayer/2/still/4
	Set MP 2 to Still 5: /atem/mplayer/2/still/5
	Set MP 2 to Still 6: /atem/mplayer/2/still/6
	Set MP 2 to Still 7: /atem/mplayer/2/still/7
	Set MP 2 to Still 8: /atem/mplayer/2/still/8
	Set MP 2 to Still 9: /atem/mplayer/2/still/9
	Set MP 2 to Still 10: /atem/mplayer/2/still/10
	Set MP 2 to Still 11: /atem/mplayer/2/still/11
	Set MP 2 to Still 12: /atem/mplayer/2/still/12
	Set MP 2 to Still 13: /atem/mplayer/2/still/13
	Set MP 2 to Still 14: /atem/mplayer/2/still/14
	Set MP 2 to Still 15: /atem/mplayer/2/still/15
	Set MP 2 to Still 16: /atem/mplayer/2/still/16
	Set MP 2 to Still 17: /atem/mplayer/2/still/17
	Set MP 2 to Still 18: /atem/mplayer/2/still/18
	Set MP 2 to Still 19: /atem/mplayer/2/still/19
	Set MP 2 to Still 20: /atem/mplayer/2/still/20

Macros:
	Get the Maximum Number of Macros: /atem/macros/get-max-number
	Stop the currently active Macro (if any): /atem/macros/stop
	Get the Name of a Macro: /atem/macros/<index>/name
	Get the Description of a Macro: /atem/macros/<index>/description
	Get whether the Macro at <index> is valid: /atem/macros/<index>/is-valid
	Run the Macro at <index>: /atem/macros/<index>/run
```

**Comment by SteffeyDev** [comment] 2018-01-12 00:23
I hadn't checked in the in-app menu due to no resolution to #49 yet, but I agree it should still be functional.  I'll see if I can push a quick fix and then we can talk about it more in #49.

**Comment by samlesbrises** [comment] 2018-01-12 10:08
thanks I will try this and let you know if that works well ;-)

**Comment by samlesbrises** [comment] 2018-01-20 11:52
thank you very mutch @sneat theses address work well :-)

**Comment by samlesbrises** [comment] 2018-01-20 12:29
just one question about the downstream address Set DSK On Ait1: /atem/dsk/on-air/1 <0|1>

when I put /atem/dsk/on-air/1 <1> the dsk goes on air and then off air very quickly, did I do somehting wrong ?

**Comment by sneat** [comment] 2018-01-21 01:35
@samlesbrises what program are you using to send the OSC addresses? Check that you aren't only sending the "on" signal when your key is pressed. You might be sending the "on" signal while the key is down, and then "off" as soon as you release it.

**Comment by samlesbrises** [comment] 2018-01-21 22:46
I use OSCulator, 

> You might be sending the "on" signal while the key is down, and then "off" as soon as you release 
> it.

even if I stay in position (without releasing the button) it happen.

I found a solution by using this code Auto-Transistion DSK1: /atem/dsk/1 and put 0:03 as timer on of the transition, and it works. When I push the button it goes to on, and if I push again it goes to off with a very short transition.

**Comment by sneat** [comment] 2018-01-21 23:20
That's very bizzare. Are you sending `1` as a float to enable it and `0` as a float to disable it?

**Closed** 2018-02-19 21:18 UTC
