### ISSUE TITLE
OSC port numbers are lost at startup 

### ISSUE THREAD

**Issue by jeffmann** [danielbuechele/atemOSC#71] opened 2018-03-27 11:03 UTC
atemOSC 2.5, macOS 10.12.6

If I change the OSC incoming/outgoing port numbers from the default 3333/4444, then when I restart atemOSC, the changes are not restored, and the ports are back to the defaults.

**Comment by SteffeyDev** [comment] 2018-03-27 15:51
I've noticed the same, I will look into it when I have the chance.  Does it save both IP addresses correctly?

**Comment by jeffmann** [comment] 2018-03-27 16:43
Yes, since #23 the IP numbers are saved, thanks for that!

**Comment by SteffeyDev** [comment] 2018-04-06 20:03
Ok, I think I found the issue but unfortunately won't be able to test for a few weeks.  If anyone has Xcode and can test, let me know.

**Comment by SteffeyDev** [comment] 2018-04-16 23:34
Ok, this should be fixed after the latest version is released.  I will leave this open until the fix is verified after the release.

**Comment by SteffeyDev** [comment] 2018-04-21 02:57
@jeffmann We just released the version with a patch, can you download and run atemOSC version 2.5.3 and check if the issue is fixed?

**Comment by jeffmann** [comment] 2018-04-21 12:31
I don't have access to the switcher at the moment. Running it without the switcher, it doesn't appear to be fixed. 

The symptoms are all the same as #23, including the "other observations" there about trashing or manually editing the prefs file, except now with the port numbers insead of the switcher IP address being lost.

- Open the app and change the IP addresses, and change the port numbers to eg. 5555/6666. Note all the changes are correctly reflected in the `cc.buechele.atemOSC.plist` preferences file.
- Quit the app. Note the changes are still there in the preferences file.
- Start the app again.

Results: the IP address changes are retained, but the port numbers in the app window revert to 3333/4444, and in the preferences file, the `incoming` and `outgoing` keys are set to `0`.

**Comment by SteffeyDev** [comment] 2018-04-21 19:46
Are you sure you are running 2.5.3? I just tested again sans-switcher and it worked fine.  I changed port numbers, quit the app, restarted, and the port numbers were restored.  The process you described sounds like what the code would have done in 2.5.2.  If you can confirm you are using the new version, I will need to know what OS you are running so that I can try and reproduce.

**Comment by SteffeyDev** [comment] 2018-04-21 19:48
Ok, so I just tested closing the app with `Force Quit` from Activity Monitor, and I can reproduce the issue.  I will see if I can figure out why.  I still can't reproduce using normal `Quit` from the app.

**Comment by SteffeyDev** [comment] 2018-04-21 19:53
Hm, yea the Force Quit issue makes me wonder again... I'll keep looking

**Comment by SteffeyDev** [comment] 2018-04-21 20:03
Ok just kidding, I found the actual issue, and fixed it.  I'll get that in the next release.  Also, for the records, this command is beautiful: `defaults read cc.buechele.atemOSC`

**Comment by SteffeyDev** [comment] 2018-07-04 16:07
@jeffmann Ok, this should finally be fixed in v2.5.4.  I'll leave this open for a few days so that you can validate if you want

**Comment by SteffeyDev** [comment] 2018-09-10 17:56
Closing this, assumed resolved.  I haven't seen this again personally since this fix, and have not heard of anyone else who has.

**Closed by SteffeyDev** 2018-09-10 17:56 UTC
Labels: bug, pending-close

**Comment by jeffmann** [comment] 2018-09-11 19:12
Sorry, I missed the notification in July... I don't have a switcher right now, but running without now retains the port numbers for me too, so I guess it's fixed, thanks!
